### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by Janpot**
This allows for automated builds on https://hub.docker.com/

### CODE REVIEW

**Comment by Janpot** [comment]
@gkellogg Thanks for the quick merge.

Are you interested in setting up an [automated build](http://docs.docker.com/docker-hub/builds/) in https://hub.docker.com/? This would publish the resulting image under your account and ensures your ownership. Note: this should only be a one time setup for you, no further management required.

In the other case my company will sync a fork and publish an image under our account, if you're ok with that. If I understand correctly your license allows for that but basic politeness requires me to ask (also, we'd prefer the first option as that would save us from having to keep a fork in sync :wink:)

**Comment by gkellogg** [comment]
I currently just push this to heroku using git, I'm really not sure what this gets me, but I'm happy to enable the docker workflow. But, if this can easily set it up to run at an alternate location automatically on push the the master (or better-yet, develop) branch, that would be useful.

**Comment by Janpot** [comment]
For your current deployment workflow, there is no benefit. For a docker based workflow it would be different. Anybody running a docker host could pull your image and run it in a single command. Be it on a laptop, a test environment or a production cluster.

docker hub can be set up to monitor one of your branches and rebuild the image on push. It would host this image publicly for anyone to pull and run.

In our case this would allow us to easily deploy one or more instances of the application in our cluster and deploy updates without having to bother with building new images or tracking your changes.

As said, we will do this ourselves if you don't. I just want to inform you, in case you prefer to publish it under your own name. If you're not a docker user and don't plan to use it in the future, the only benefit might be that you provide more options for users of this package to deploy it to where they want.

**Comment by Janpot** [comment]
FYI: https://registry.hub.docker.com/u/woorank/rdf-distiller/
For now it just tracks the develop branch. I will change that to master as soon as the dockerfile hits that branch.

**Pull request merged**
